keyboard_strings: dict = {
    "get_groups": "Список групп",
    "add_group": "Добавить группу",
    "back": "Назад",
    "get_text": "Текст",
    "get_schedule": "Дата отправки",
    "edit": "Редактировать",
    "edit_date": "Редактировать дату",
    "edit_time": "Редактировать время",
    "cancel_edit": "Назад",
    "get_default_text": "Текст по умолчанию",
    "edit_price": "Редактировать цену",
    "edit_amount": "Количество занятий",
    "edit_text": "Редактировать текст",
    "groups_send_messages": "Рассылки",
    "get_amount": "Количество занятий",
    "edit_group_schedule": "Редактировать",
    "add_amount": "Добавить количество",
    "delete_amount": "Удалить количество"
}
